"""add person outreach obs

Revision ID: 1ee7ff0b9bc9
Revises: 6ecf277c74ba
Create Date: 2026-08-31 12:17:51.102578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee7ff0b9bc9'
down_revision: Union[str, Sequence[str], None] = '6ecf277c74ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_email_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('outreach', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_method', sa.String(length=100), nullable=True),
    sa.Column('verification_result', sa.String(length=100), nullable=True),
    sa.Column('pattern_inferred', sa.String(length=100), nullable=True),
    sa.Column('source_urls', sa.Text(), nullable=True),
    sa.Column('found_public_emails', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_email_observations_company_id'), 'person_email_observations', ['company_id'], unique=False)
    op.create_index(op.f('ix_person_email_observations_normalized_email'), 'person_email_observations', ['normalized_email'], unique=False)
    op.create_index(op.f('ix_person_email_observations_observed_at'), 'person_email_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_person_email_observations_person_id'), 'person_email_observations', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_email_observations_provider_name'), 'person_email_observations', ['provider_name'], unique=False)
    op.create_index(op.f('ix_person_email_observations_source_id'), 'person_email_observations', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_email_observations_source_id'), table_name='person_email_observations')
    op.drop_index(op.f('ix_person_email_observations_provider_name'), table_name='person_email_observations')
    op.drop_index(op.f('ix_person_email_observations_person_id'), table_name='person_email_observations')
    op.drop_index(op.f('ix_person_email_observations_observed_at'), table_name='person_email_observations')
    op.drop_index(op.f('ix_person_email_observations_normalized_email'), table_name='person_email_observations')
    op.drop_index(op.f('ix_person_email_observations_company_id'), table_name='person_email_observations')
    op.drop_table('person_email_observations')
    # ### end Alembic commands ###
