"""add website performance and technology observations

Revision ID: 3c6935186aaf
Revises: 515b92a322da
Create Date: 2026-08-17 13:51:08.912193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6935186aaf'
down_revision: Union[str, Sequence[str], None] = '515b92a322da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_observations_company_id'), 'technology_observations', ['company_id'], unique=False)
    op.create_index(op.f('ix_technology_observations_name'), 'technology_observations', ['name'], unique=False)
    op.create_index(op.f('ix_technology_observations_observed_at'), 'technology_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_technology_observations_provider_name'), 'technology_observations', ['provider_name'], unique=False)
    op.create_index(op.f('ix_technology_observations_source_id'), 'technology_observations', ['source_id'], unique=False)
    op.create_table('website_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('first_contentful_paint_ms', sa.Float(), nullable=True),
    sa.Column('largest_contentful_paint_ms', sa.Float(), nullable=True),
    sa.Column('cumulative_layout_shift', sa.Float(), nullable=True),
    sa.Column('total_blocking_time_ms', sa.Float(), nullable=True),
    sa.Column('speed_index_ms', sa.Float(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_performance_company_id'), 'website_performance', ['company_id'], unique=False)
    op.create_index(op.f('ix_website_performance_observed_at'), 'website_performance', ['observed_at'], unique=False)
    op.create_index(op.f('ix_website_performance_provider_name'), 'website_performance', ['provider_name'], unique=False)
    op.create_index(op.f('ix_website_performance_source_id'), 'website_performance', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_performance_source_id'), table_name='website_performance')
    op.drop_index(op.f('ix_website_performance_provider_name'), table_name='website_performance')
    op.drop_index(op.f('ix_website_performance_observed_at'), table_name='website_performance')
    op.drop_index(op.f('ix_website_performance_company_id'), table_name='website_performance')
    op.drop_table('website_performance')
    op.drop_index(op.f('ix_technology_observations_source_id'), table_name='technology_observations')
    op.drop_index(op.f('ix_technology_observations_provider_name'), table_name='technology_observations')
    op.drop_index(op.f('ix_technology_observations_observed_at'), table_name='technology_observations')
    op.drop_index(op.f('ix_technology_observations_name'), table_name='technology_observations')
    op.drop_index(op.f('ix_technology_observations_company_id'), table_name='technology_observations')
    op.drop_table('technology_observations')
    # ### end Alembic commands ###
