"""add person tables

Revision ID: 85678a799751
Revises: 04240f853cf4
Create Date: 2026-08-19 10:08:18.089150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85678a799751'
down_revision: Union[str, Sequence[str], None] = '04240f853cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('outreach', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_company_id'), 'people', ['company_id'], unique=False)
    op.create_index(op.f('ix_people_linkedin_url'), 'people', ['linkedin_url'], unique=False)
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_index(op.f('ix_people_normalized_name'), 'people', ['normalized_name'], unique=False)
    op.create_table('person_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('decision_maker_score', sa.Integer(), nullable=True),
    sa.Column('decision_maker_role_group', sa.String(length=50), nullable=True),
    sa.Column('decision_maker_confidence', sa.String(length=50), nullable=True),
    sa.Column('decision_maker_reasons', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_observations_company_id'), 'person_observations', ['company_id'], unique=False)
    op.create_index(op.f('ix_person_observations_observed_at'), 'person_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_person_observations_person_id'), 'person_observations', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_observations_provider_name'), 'person_observations', ['provider_name'], unique=False)
    op.create_index(op.f('ix_person_observations_source_id'), 'person_observations', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_observations_source_id'), table_name='person_observations')
    op.drop_index(op.f('ix_person_observations_provider_name'), table_name='person_observations')
    op.drop_index(op.f('ix_person_observations_person_id'), table_name='person_observations')
    op.drop_index(op.f('ix_person_observations_observed_at'), table_name='person_observations')
    op.drop_index(op.f('ix_person_observations_company_id'), table_name='person_observations')
    op.drop_table('person_observations')
    op.drop_index(op.f('ix_people_normalized_name'), table_name='people')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_index(op.f('ix_people_linkedin_url'), table_name='people')
    op.drop_index(op.f('ix_people_company_id'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
