"""add website craw & links

Revision ID: b0298b5a2227
Revises: cb1a2d4f7e83
Create Date: 2026-08-15 19:25:35.097092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0298b5a2227'
down_revision: Union[str, Sequence[str], None] = 'cb1a2d4f7e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_crawls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_crawls_company_id'), 'website_crawls', ['company_id'], unique=False)
    op.create_index(op.f('ix_website_crawls_content_hash'), 'website_crawls', ['content_hash'], unique=False)
    op.create_table('website_crawl_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_crawl_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_crawl_id'], ['website_crawls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_crawl_id', 'url', name='uq_website_crawl_links_crawl_url')
    )
    op.create_index(op.f('ix_website_crawl_links_website_crawl_id'), 'website_crawl_links', ['website_crawl_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_crawl_links_website_crawl_id'), table_name='website_crawl_links')
    op.drop_table('website_crawl_links')
    op.drop_index(op.f('ix_website_crawls_content_hash'), table_name='website_crawls')
    op.drop_index(op.f('ix_website_crawls_company_id'), table_name='website_crawls')
    op.drop_table('website_crawls')
    # ### end Alembic commands ###
