"""add contacts tables

Revision ID: b281c456b843
Revises: c3e1a475438f
Create Date: 2026-08-19 09:29:49.769442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b281c456b843'
down_revision: Union[str, Sequence[str], None] = 'c3e1a475438f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_observations_company_id'), 'contact_observations', ['company_id'], unique=False)
    op.create_index(op.f('ix_contact_observations_kind'), 'contact_observations', ['kind'], unique=False)
    op.create_index(op.f('ix_contact_observations_observed_at'), 'contact_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_contact_observations_provider_name'), 'contact_observations', ['provider_name'], unique=False)
    op.create_index(op.f('ix_contact_observations_source_id'), 'contact_observations', ['source_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_kind'), 'contacts', ['kind'], unique=False)
    op.create_index(op.f('ix_contacts_normalized_value'), 'contacts', ['normalized_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_normalized_value'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_kind'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_contact_observations_source_id'), table_name='contact_observations')
    op.drop_index(op.f('ix_contact_observations_provider_name'), table_name='contact_observations')
    op.drop_index(op.f('ix_contact_observations_observed_at'), table_name='contact_observations')
    op.drop_index(op.f('ix_contact_observations_kind'), table_name='contact_observations')
    op.drop_index(op.f('ix_contact_observations_company_id'), table_name='contact_observations')
    op.drop_table('contact_observations')
    # ### end Alembic commands ###
