"""add email messages

Revision ID: d750cfce9fa1
Revises: 30d3155efc9e
Create Date: 2026-09-21 18:57:11.793168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd750cfce9fa1'
down_revision: Union[str, Sequence[str], None] = '30d3155efc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('reply_to', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    op.create_index(op.f('ix_email_messages_company_id'), 'email_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_messages_person_id'), 'email_messages', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_person_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_company_id'), table_name='email_messages')
    op.drop_table('email_messages')
    # ### end Alembic commands ###
